# Numpy y Scipy

In [1]:
import numpy as np

Para aquellos que trabajen con Matlab© existe ;

https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html

### Creando arreglos

Podemos convertir una lista o tuple a arreglo usando `np.array()`:

In [2]:
a = np.array([1,2,3], float)
print(a)

[ 1.  2.  3.]


In [3]:
b = np.array([[1,2,3],[4,5,6]],float)
print(b)

[[ 1.  2.  3.]
 [ 4.  5.  6.]]


O inicializar una secuencia de valores secuenciales con `np.arange(`_inicio_, _final_, _incremento_`)`:

In [4]:
c = np.arange(-0.5, 0.5, 0.05)
print(c)

[ -5.00000000e-01  -4.50000000e-01  -4.00000000e-01  -3.50000000e-01
  -3.00000000e-01  -2.50000000e-01  -2.00000000e-01  -1.50000000e-01
  -1.00000000e-01  -5.00000000e-02  -1.11022302e-16   5.00000000e-02
   1.00000000e-01   1.50000000e-01   2.00000000e-01   2.50000000e-01
   3.00000000e-01   3.50000000e-01   4.00000000e-01   4.50000000e-01]


Lo que también se puede lograr con `np.linspace(`_inicio_, _final_, _numero de valores_`)`:

In [5]:
d = np.linspace(-0.5, 0.5, 25)
print(d)

[-0.5        -0.45833333 -0.41666667 -0.375      -0.33333333 -0.29166667
 -0.25       -0.20833333 -0.16666667 -0.125      -0.08333333 -0.04166667
  0.          0.04166667  0.08333333  0.125       0.16666667  0.20833333
  0.25        0.29166667  0.33333333  0.375       0.41666667  0.45833333
  0.5       ]


Numpy tiene también métodos para inicializar arreglos de zeros (`np.zeros()`) y unos (`np.ones()`), estos métodos toman como parámetro una tupla con las dimensiones:

In [6]:
e = np.zeros((3,3))
print(e)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [7]:
f = np.ones((3,3,3))
print(f)

[[[ 1.  1.  1.]
  [ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]
  [ 1.  1.  1.]]]


__Nota__: existen también los métodos (`np.zeros_like()`) y unos (`np.ones_like()`) que toman un arreglo y crean otro con las mismas dimensiones.

### Obteniendo información sobre los arreglos

Para conocer el tamaño de algún arreglo podemos usar la propiedad `arreglo.size`:

In [8]:
print("El tamaño de d es {}".format(d.size))
print("El tamaño de e es {}".format(e.size))
print("El tamaño de f es {}".format(np.size(f)))

El tamaño de d es 25
El tamaño de e es 9
El tamaño de f es 27


Para conocer la forma de algún arreglo podemos usar la propiedad `arreglo.shape`:

In [9]:
print("La forma de d es {}".format(d.shape))
print("La forma de e es {}".format(e.shape))
print("La forma de f es {}".format(np.shape(f)))

La forma de d es (25,)
La forma de e es (3, 3)
La forma de f es (3, 3, 3)


Y, para conocer el número de dimensiones `arreglo.ndim`:

In [10]:
print("d tiene {} dimensiones".format(d.ndim))
print("e tiene {} dimensiones".format(e.ndim))
print("f tiene {} dimensiones".format(np.ndim(f)))

d tiene 1 dimensiones
e tiene 2 dimensiones
f tiene 3 dimensiones


Para accesar o modificar los elementos de un arreglo usamos __[]__, igual que las listas o tuplas.

In [11]:
print(a[1:])

[ 2.  3.]


In [12]:
a[0] = 5
print(a)

[ 5.  2.  3.]


Pero se puede usar la coma dentro de los corchetes.

In [13]:
print(b)

[[ 1.  2.  3.]
 [ 4.  5.  6.]]


In [14]:
print(b[:, 1:2])

[[ 2.]
 [ 5.]]


### Operaciones simples:

In [15]:
print(b.T)

[[ 1.  4.]
 [ 2.  5.]
 [ 3.  6.]]


In [16]:
print(b + b)

[[  2.   4.   6.]
 [  8.  10.  12.]]


In [17]:
print(b * b)

[[  1.   4.   9.]
 [ 16.  25.  36.]]


In [18]:
print(b ** 2)

[[  1.   4.   9.]
 [ 16.  25.  36.]]


In [19]:
print(b.dot(np.array([1, 2, 3])))

[ 14.  32.]
