## Ejercicio 1 - Numpy

Se quieren calcular las reacciones y el desplazamiento de un sistema de dos resortes de un grado de libertad con el movimento restringido en los extremos.

![Sistema 1D de dos resortes](img/Resortes-1D.png)

Donde $D_1$, $D_2$, $D_3$ son los desplazamientos de cada uno de los puntos, $Q_2$ y $Q_3$ son las reacciones y $Q_1$ es la fuerza aplicada. Los resortes tienen la rigidez $k_1$ y $k_2$.

De este sistema se obtiene la sigiente ecuación matricial:
$$
\left[\begin{array}{ccc}
k_{1}+k_{2} & -k_{1} & -k_{2}\\
-k_{1} & k_{1} & 0\\
-k_{2} & 0 & k_{2}
\end{array}\right]\left[\begin{array}{c}
D_{1}\\
D_{2}\\
D_{3}
\end{array}\right]=\left[\begin{array}{c}
Q_{1}\\
Q_{2}\\
Q_{3}
\end{array}\right]
$$

Los datos que tenemos son:
$$Q_1 = 50\,N$$
$$k_1 = 500\,N/m$$
$$k_2 = 750\,N/m$$

Por el esquema conocemos que:
$$D_2 = 0$$
$$D_3 = 0$$

Substituyendo los valores $0$:
$$
\left[\begin{array}{ccc}
k_{1}+k_{2} & -k_{1} & -k_{2}\\
-k_{1} & k_{1} & 0\\
-k_{2} & 0 & k_{2}
\end{array}\right]\left[\begin{array}{c}
D_{1}\\
0\\
0
\end{array}\right]=\left[\begin{array}{c}
Q_{1}\\
Q_{2}\\
Q_{3}
\end{array}\right]
$$


Y reorganizando:
$$
\left[\begin{array}{ccc}
k_{1}+k_{2} & 0 & 0\\
-k_{1} & -1 & 0\\
-k_{2} & 0 & -1
\end{array}\right]\left[\begin{array}{c}
D_{1}\\
Q_{2}\\
Q_{3}
\end{array}\right]=\left[\begin{array}{c}
Q_{1}\\
0\\
0
\end{array}\right]
$$


Substituyendo los valores:
$$
\left[\begin{array}{ccc}
1250 & 0 & 0\\
-500 & -1 & 0\\
-750 & 0 & -1
\end{array}\right]\left[\begin{array}{c}
D_{1}\\
Q_{2}\\
Q_{3}
\end{array}\right]=\left[\begin{array}{c}
50\\
0\\
0
\end{array}\right]
$$
____
**Ejercicio**: Resuelve este sistema del tipo $Ax = b$ con la función `scipy.linalg.solve`:
    x = solve(A,b)

In [1]:
import numpy as np
import scipy.linalg as linalg

In [2]:
k1 = 500
k2 = 750

A = np.array([[k1 + k2, 0, 0],[-k1, -1, 0],[-k2, 0, -1]], float)
print(A)

[[  1.25000000e+03   0.00000000e+00   0.00000000e+00]
 [ -5.00000000e+02  -1.00000000e+00   0.00000000e+00]
 [ -7.50000000e+02   0.00000000e+00  -1.00000000e+00]]


In [3]:
b = np.array([50, 0, 0], float)
print(b)

[ 50.   0.   0.]


In [4]:
D1, Q2, Q3 = linalg.solve(A,b)
print("El desplazamiento D1 es {} m.".format(D1))
print("La reacción Q2 es {} N.".format(Q2))
print("La reacción Q2 es {} N.".format(Q3))

El desplazamiento D1 es 0.04 m.
La reacción Q2 es -20.0 N.
La reacción Q2 es -30.0 N.
